


# only whitelist
package_list=(com.android.shell com.android.providers.downloads com.google.android.apps.translate io.github.chsbuffer.revancedxposed com.google.android.gsf com.google.android.printservice.recommendation com.google.android.onetimeinitializer com.google.android.configupdater com.android.vending com.google.android.googlequicksearchbox com.google.android.webview me.weishu.kernelsu com.xhey.xcamera org.thunderdog.challegram com.android.chrome bin.mt.termex com.twitter.android com.google.android.inputmethod.latin com.github.android com.google.android.gms com.google.android.apps.authenticator2 com.reddit.frontpage com.google.android.apps.maps bin.mt.plus com.google.android.youtube com.termux)
appclones=() 

index=2081
device="tun3"
uid=0
gid=3005
fwmark=200

local_cidr=(0.0.0.0/8 10.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 172.16.0.0/12 192.0.0.0/24 192.0.2.0/24 192.88.99.0/24 192.168.0.0/16 198.51.100.0/24 203.0.113.0/24 224.0.0.0/4 240.0.0.0/4 255.0.0.0/4 255.255.255.0/24 255.255.255.255/32)

local_cidr6=(::/127 2408:8000::/20 2409:8000::/20 240a:4000::/21 240e::/18 fc00::/7 fe80::/10 ff00::/8)
